name:
version: 0.0.1
build: 1
encrypt stacks: false
multiple instances: false
relaunch in background: false
creator code:
application data folder:
  user:
    default:
    macos:
    windows:
    linux:
    ios:
    android:
  shared:
    default:
    macos:
    windows:
    linux:
preferences filename:
  user:
    default:
    macos:
    windows:
    linux:
    ios:
    android:
  shared:
    default:
    macos:
    windows:
    linux:
ui:
  - folder: ./ui
libraries:
  - folder: ./libraries
frontscripts:
  - folder: ./frontscripts
backscripts:
  - folder: ./backscripts
helpers:
  - folder: ./helpers
  - filename: ../../sql-yoga
  - filename: "[[FRAMEWORK]]/helpers/preferences"
behaviors:
  - folder: ./behaviors

sql yoga:
  database key: default
  configuration files:
    - filename: ./database/schema.yml
    - filename: ./database/connections.yml
    - filename: ./database/migrations.yml
    - filename: ./database/query templates.yml
    - filename: ./database/table objects.yml

build folder: ../builds
build profiles:
  all profiles:
    packager callbacks stackfile:
    certificates:
      macos:
        name:
    copy files:
      all platforms:
        - filename: assets
      macos:
      windows:
      linux:
      ios:
      android:
  release:
  beta:
